
[mysql]
dialect = "mysql"
host = "localhost"
port = 3306
user = "root"
password = "root123"
database = "youtube"

[mongodb]
connection_url = "mongodb+srv://krishnanradha957:8kAsJkX0GdyBvb1v@cluster0.vuvetlv.mongodb.net/youtube"

