[postgres]
dialect = "postgresql"
host = "dpg-ciqhei59aq0dcpts1ij0-a"
port = 5432
user = "radhakrishnan"
password = "demao"
database = "Smo1k1H9nUNsFn7TxNj1d97M6B0QgLCv"

[mongodb]
connection_url = "mongodb+srv://radhakrishnanganapathy5:pnvGVTD7rM3kgFTN@radhakrishnan.cozk1ms.mongodb.net/youtube"

