
[mysql]
dialect = "mysql"
host = "localhost"
port = 3306
user = "root"
password = "root123"
database = "youtube"

[mongodb]
connection_url = "mongodb+srv://radhakrishnan:radhaKRISHNAN96@cluster0.fx6ouyb.mongodb.net/balancesheet?retryWrites=true&w=majority"

